config/routes.rb
Rails.application.routes.draw do

  resources :customers do
    resources :notes
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "customers#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :notes
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: %i[ show edit update destroy ]

  # GET /customers or /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1 or /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers or /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully created." }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1 or /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to customer_url(@customer), notice: "Customer was successfully updated." }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1 or /customers/1.json
  def destroy
    @customer.destroy!

    respond_to do |format|
      format.html { redirect_to customers_url, notice: "Customer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def customer_params
      params.require(:customer).permit(:name)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_customer
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes or /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1 or /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = @customer.notes.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes or /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to [@note.customer, @note], notice: "Note was successfully created." }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1 or /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to [@note.customer, @note], notice: "Note was successfully updated." }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1 or /notes/1.json
  def destroy
    @note.destroy!

    respond_to do |format|
      format.html { redirect_to [@note.customer, @note], notice: "Note was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:customer_id])
    end

    def set_note
      @note = Note.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.require(:note).permit(:content, :customer_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/customers/_customer.html.erb
<div id="<%= dom_id customer %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= customer.name %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this customer", customer, class: "bg-blue-600 text-white rounded-lg py-3 px-5 inline-block font-medium" %>
    <%= link_to "Edit this customer", edit_customer_path(customer), class: "bg-blue-600 text-white rounded-lg py-3 ml-2 px-5 inline-block font-medium" %>
    <%= link_to "Add notes", new_customer_note_path(customer), class: "bg-blue-600 text-white rounded-lg py-3 ml-2 px-5 inline-block font-medium" %>
    <%= link_to "Show notes", [customer, :notes], class: "bg-blue-600 text-white rounded-lg py-3 ml-2 px-5 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/customers/_form.html.erb
<%= form_with(model: customer, class: "contents") do |form| %>
  <% if customer.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
        <% customer.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing customer</h1>
  <%= render "form", customer: @customer %>
  <%= link_to "Show this customer", @customer, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
</div>

app/views/customers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Customers</h1>
    <%= link_to "New customer", new_customer_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="customers" class="min-w-full">
    <%= render @customers %>
  </div>
</div>

app/views/customers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New customer</h1>

  <%= render "form", customer: @customer %>

  <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/customers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @customer %>
    <%= link_to "Edit this customer", edit_customer_path(@customer), class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this customer", customer_path(@customer), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
    </div>
    <%= link_to "Back to customers", customers_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CustomerCrm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, url: [customer, note], class: "contents") do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>
      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="my-5">
    <%= form.label :content %>
    <%= form.text_area :content, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :customer_id %>
    <%= form.text_field :customer_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Content:</strong>
    <%= note.content %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Customer:</strong>
    <%= note.customer_id %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this note", [note.customer, note], class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
    <%= link_to "Edit this note", [:edit, note.customer, note], class: "rounded-lg py-3 ml-2 px-5 bg-blue-600 text-white inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/notes/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing note</h1>
  <%= render "form", note: @note, customer: @customer %>
  <%= link_to "Show this note", [@note.customer, @note], class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  <%= link_to "Back to notes", [@note.customer, @note], class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
</div>

app/views/notes/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Notes for: <%= @customer.name %></h1>
    <%= link_to "Back to customers", customers_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="notes" class="min-w-full">
    <%= render @notes %>
  </div>
</div>

app/views/notes/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New note</h1>
  <%= render "form", note: @note, customer: @customer %>
  <%= link_to "Back to notes", customer_notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
</div>

app/views/notes/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <%= render @note %>
    <%= link_to "Edit this note", [:edit, @note.customer, @note], class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this note", [@note.customer, @note], method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-blue-600 text-white font-medium" %>
    </div>
    <%= link_to "Back to notes", customer_notes_path, class: "ml-2 rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium" %>
  </div>
</div>